import 'dart:convert';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppLocalization {
  final Locale locale;
  late Map<String, String> _localizedStrings;

  AppLocalization(this.locale);

  static const LocalizationsDelegate<AppLocalization> delegate =
      _AppLocalizationDelegate();

  static AppLocalization? of(BuildContext context) {
    return Localizations.of<AppLocalization>(context, AppLocalization);
  }

  Future<bool> load() async {
    final String jsonString = await rootBundle.loadString(
      'lib/l10n/${locale.languageCode}.json',
    );

    Map<String, dynamic> jsonMap = json.decode(jsonString);

    _localizedStrings = jsonMap.map(
      (key, value) => MapEntry(key, value.toString()),
    );

    return true;
  }

  String translate(String key) {
    return _localizedStrings[key] ?? '** $key not found';
  }
}

class _AppLocalizationDelegate extends LocalizationsDelegate<AppLocalization> {
  const _AppLocalizationDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['en', 'hi', 'gu'].contains(locale.languageCode);

  @override
  Future<AppLocalization> load(Locale locale) async {
    AppLocalization localization = AppLocalization(locale);
    await localization.load();
    return localization;
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalization> old) =>
      false;
}

class AppTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': AppTranslation.en,
    'hi': AppTranslation.hi,
    'gu': AppTranslation.gu,
  };

  static final Map<String, String> en = {
    "appName": "Sumul Transport",
    "homeTitle": "Home",
    "welcomeMessage": "Welcome to Home",
    "alert": "Alert",
    "error": "Error",
    "warning": "Warning",
    "success": "Success",
    "required": "Required",
    "yes": "Yes",
    "no": "No",
    "ok": "Ok",
    "canceled": "Cancel",
    "save": "Save",
    "clear": "Clear",
    "capture": "Capture",
    "noImageCaptured": "No Image Captured",
    "settings": "Settings",
    "logout": "Logout",
    "submit": "Submit",
    "logOutText": "Are you sure you want to logout",
    "noRecordFound": "No Record found for",
    "loginScreenLoginText": "Login",
    "loginScreenSignupBtnText": "Signup",
    "loginScreenEmailText": "Email",
    "loginScreenVerifyOtpText": "Verify OTP",
    "loginScreenSendOtpBtnText": "Send OTP",
    "loginScreenResendOtpText": "Resend OTP",
    "loginScreenHintMobileNumber": "Mobile Number",
    "loginScreenPleaseEnterUsername": "Please enter valid employee code",
    "loginScreenEnterMobileNumber": "Enter your mobile number",
    "loginScreenSmsSentMessage": "An SMS with 4-digit OTP was sent to",
    "loginScreenValidOtp": "Please enter valid 4-digit OTP",
    "loginScreenChange": "Change",
    "formVehicleNo": "Vehicle No.",
    "formSearchVehicleNumber": "Search vehicle number",
    "formSearchAgent": "Search agent",
    "formDate": "Date",
    "formInText": "In",
    "formOut": "Out",
    "formInDate": "In Date",
    "formOutDate": "Out Date",
    "formContractor": "Contractor",
    "formMobileNo": "Mobile No",
    "formTotalTime": "Total Time",
    "currentStatus": "Current Status",
    "formEmpNo": "Cust. No",
    "formEmpName": "Emp Name",
    "formName": "Name",
    "yourAgent": "Select Agent",
    "category": "Category",
    "categoryChooseCategory": "Choose Category",
    "categoryDairy": "Dairy",
    "categoryOther": "Other",
    "categoryBakery": "Bakery",
    "categoryMilk": "Milk",
    "categorypProduct": "Product",
    "apptitle1": "SURAT-TAPI DISTRICT CO-OPERATIVE MILK PRODUCER'S UNION LTD.",
    "apptitle2": "SUMUL DAIRY, SURAT - 395 008",
    "dashboardBalance": "Balance",
    "dashboardTime": "Time",
    "total": "Total",
    "report": "Reports",
    "information": "Information",
    "menuHeaderOrderManagement": "Order Management",
    "menuHeaderOrderHistory": "View Order",
    "menuHeaderCashManagement": "Cash Management",
    "menuHeaderReports": "Reports",
    "menuplaceOrder": "Place Order",
    "menucopyOrder": "Copy Order",
    "menudailySlip": "Daily Slip",
    "menuchangepassword": "Change Password",
    "menuchangepasswordoldpassword": "Old Password",
    "menuchangepasswordnewpassword": "New Password",
    "menuchangepasswordnewcnfpassword": "Confirm Password",
    "menuchangepasswordcreatenew": "Create your new password",
    "menuaboutus": "About us",
    "menunewsalert": "News And Alerts",
    "menupricelist": "Price List",
    "menuyearlystatement": "Yearly Monthly StateMent",
    "menudatewisebalance": "Date Wise Balance",
    "menuviewgatepassorder": "View GatePass Order",
    "menuviewpreviousorder": "View Previous Order",
    "menuviewpreviousextraorder": "View Previous Extra Order",
    "menugatepassorder": "GatePass Order",
    "menubakeryorder": "Bakery - Order (Bakery Vehicle)",
    "menuextraorder": "Extra Order",
    "menucashentry": "Cash Entry",
    "menuviewcashentry": "View Cash Entry",
    "menuconfirmorder": "Confirm Order",
    "menulogoutfromalldevice": "Logout All",
    "menubacktocategory": "MainCategory",
    "menucratebalance": "Crate Balance",
    "menuledger": "Ledger",
    "menucd": "Credit Debit Information",
    "menucrate": "Crate",
    "ordertime": "Order time",
    "allordertime": "All order time",
    "hasended": "has ended",
    "ordertimenotice": "Order Time Notice",
    "orderAmount": "Order Amount",
    "changeDate": "Change Date",
    "pouch": "Pouch",
    "crates": "Crates",
    "pending": "Pending",
    "completed": "Completed",
    "edit": "Edit",
    "orderNo": "Order No",
    "qty": "Qty",
    "currency": "Currency",
    "perDayLimit": "Per day limit is 20000",
    "cancel": "Cancelled",
    "slipNo": "Slip No",
    "denomination": "Denomination",
    "nos": "Nos",
    "amount": "Amount",
    "openingBalance": "Deposite Opening Balance",
    "netClosingBalance": "Net Cl. Bal.",
    "closingLessDeposit": "Cl. (Less Deposit)",
    "times": "Times",
    "routes": "Routes",
    "dateWiseBalanceSummary": "Date-wise Balance Summary",
    "despatch": "Despatch",
    "deposit": "Deposit",
    "financialYear": "Financial Year",
    "selectMonth": "Select Month",
    "optional": "Optional",
    "month": "Month",
    "download": "Download",
    "viewStatement": "View Statement",
    "exitAppTitle": "Exit App",
    "exitAppMessage": "Are you sure you want to exit?",
    "youhave": "You have",
    "newnotifications": "new notifications",
    "received": "received",
    "confirm": "Confirm Order",
    "details": "Details",
    "back": "Back",
    "gatepassmultipliermessage": "Please enter pouch in multiples — like",
  };

  static final Map<String, String> hi = {
    "appName": "सुमुल ग्राहक",
    "homeTitle": "मुख्य पृष्ठ",
    "welcomeMessage": "होम पर आपका स्वागत है",
    "alert": "चेतावनी",
    "error": "त्रुटि",
    "warning": "चेतावनी",
    "success": "सफलता",
    "required": "आवश्यक",
    "yes": "हाँ",
    "no": "नहीं",
    "ok": "ठीक है",
    "canceled": "रद्द करें",
    "save": "उमेरो",
    "clear": "साफ करें",
    "capture": "कैप्चर",
    "noImageCaptured": "कोई फोटो कैप्चर नहीं हुई",
    "settings": "सेटिंग्स",
    "logout": "लॉगआउट",
    "submit": "जमा करें",
    "logOutText": "क्या आप वाकई लॉगआउट करना चाहते हैं?",
    "noRecordFound": "कोई रिकॉर्ड नहीं मिला",
    "loginScreenLoginText": "लॉगिन",
    "loginScreenSignupBtnText": "साइनअप",
    "loginScreenEmailText": "ईमेल",
    "loginScreenVerifyOtpText": "ओटीपी चेक करें",
    "loginScreenSendOtpBtnText": "ओटीपी भेजें",
    "loginScreenResendOtpText": "ओटीपी पुनः भेजें",
    "loginScreenHintMobileNumber": "मोबाइल नंबर",
    "loginScreenPleaseEnterUsername": "कृपया मान्य ग्राहक कोड दर्ज करें",
    "loginScreenEnterMobileNumber": "अपना मोबाइल नंबर दर्ज करें",
    "loginScreenSmsSentMessage": "4-अंकों वाला ओटीपी इस नंबर पर भेजा गया है",
    "loginScreenValidOtp": "कृपया मान्य 4-अंकों का ओटीपी दर्ज करें",
    "loginScreenChange": "बदलें",
    "formVehicleNo": "वाहन नंबर",
    "formSearchVehicleNumber": "वाहन नंबर खोजें",
    "formSearchAgent": "ग्राहक खोजें",
    "formDate": "तारीख",
    "formInText": "प्रवेश",
    "formOut": "प्रस्थान",
    "formInDate": "प्रवेश तारीख",
    "formOutDate": "प्रस्थान तारीख",
    "formContractor": "ठेकेदार",
    "formMobileNo": "मोबाइल नंबर",
    "formTotalTime": "कुल समय",
    "currentStatus": "वर्तमान स्थिति",
    "formEmpNo": "ग्राहक नंबर",
    "formEmpName": "ग्राहक नाम",
    "formName": "नाम",
    "yourAgent": "आपका ग्राहक",
    "category": "कैटेगरी",
    "categoryChooseCategory": "कैटेगरी चुनें",
    "categoryDairy": "डेयरी",
    "categoryOther": "अन्य",
    "categoryBakery": "बेकरी",
    "categoryMilk": "दूध",
    "categorypProduct": "उत्पाद",
    "apptitle1": "सूरत-तापी जिला सहकारी दुग्ध उत्पादक संघ लि.",
    "apptitle2": "सुमुल डेयरी, सूरत - 395 008",
    "dashboardBalance": "बैलेंस किंमत",
    "dashboardTime": "समय",
    "total": "कुल",
    "report": "रिपोर्ट्स",
    "information": "जानकारी",
    "menuHeaderOrderManagement": "ऑर्डर मैनेजमेंट",
    "menuHeaderOrderHistory": "पिछला ऑर्डर",
    "menuHeaderCashManagement": "कैश मैनेजमेंट",
    "menuHeaderReports": "रिपोर्ट्स",
    "menuplaceOrder": "ऑर्डर करें",
    "menucopyOrder": "कोपी ऑर्डर",
    "menudailySlip": "डेली स्लिप",
    "menuchangepassword": "पासवर्ड बदलें",
    "menuchangepasswordoldpassword": "पुराना पासवर्ड",
    "menuchangepasswordnewpassword": "नया पासवर्ड",
    "menuchangepasswordnewcnfpassword": "पासवर्ड की पुष्टि करें",
    "menuchangepasswordcreatenew": "नया पासवर्ड बनाएं",
    "menuaboutus": "हमारे बारे में",
    "menunewsalert": "न्यूज़ और अलर्ट",
    "menupricelist": "प्राइस लिस्ट",
    "menuyearlystatement": "वार्षिक मासिक पत्रक",
    "menudatewisebalance": "डेट वाइज़ बैलेंस",
    "menuviewgatepassorder": "गेटपास ऑर्डर देखें",
    "menuviewpreviousorder": "पिछला ऑर्डर देखें",
    "menuviewpreviousextraorder": "पिछला अधिक ऑर्डर देखें",
    "menugatepassorder": "गेटपास ऑर्डर",
    "menubakeryorder": "बेकरी - ऑर्डर (बेकरी वाहन)",
    "menuextraorder": "अधिक ऑर्डर",
    "menucashentry": "कैश एन्ट्री",
    "menuviewcashentry": "कैश एन्ट्री देखें",
    "menuconfirmorder": "कन्फर्म ऑर्डर",
    "menulogoutfromalldevice": "सभी डिवाइस से लॉगआउट करें",
    "menubacktocategory": "मुख्य कैटेगरी",
    "menucratebalance": "क्रेट बैलेंस",
    "menuledger": "लेजर",
    "menucd": "क्रे. डेब.",
    "menucrate": "क्रेट",
    "ordertime": "ऑर्डर समय",
    "allordertime": "सभी ऑर्डर समय",
    "hasended": "समाप्त हो गया है।",
    "ordertimenotice": "ऑर्डर समय सूचना",
    "orderAmount": "ऑर्डर किंमत",
    "changeDate": "तारीख बदलें",
    "pouch": "पाउच",
    "crates": "क्रेट्स",
    "pending": "बकाया",
    "completed": "पूर्ण",
    "orderNo": "ऑर्डर नंबर",
    "edit": "बदलें",
    "qty": "क्वांटिटी",
    "currency": "करंसी",
    "perDayLimit": "प्रति दिन की सीमा 20000 है",
    "cancel": "रद्द किया गया",
    "slipNo": "स्लिप नंबर",
    "denomination": "प्राइस",
    "nos": "संख्या",
    "amount": "किंमत",
    "openingBalance": "डिपॉज़िट ओपनिंग बैलेंस",
    "netClosingBalance": "नेट क्लोज़िंग बैलेंस",
    "closingLessDeposit": "क्लोज़िंग (लेस डिपॉज़िट)",
    "times": "टाइम्स",
    "routes": "रूट्स",
    "dateWiseBalanceSummary": "डेट-वाइज़ बैलेंस",
    "despatch": "डिस्पैच",
    "deposit": "डिपॉज़िट",
    "financialYear": "वित्तीय वर्ष",
    "selectMonth": "महीना चुनें",
    "optional": "वैकल्पिक",
    "month": "महीना",
    "download": "डाउनलोड",
    "viewStatement": "स्टेटमेंट देखें",
    "exitAppTitle": "एप्लिकेशन बंद करें",
    "exitAppMessage": "क्या आप वाकई एप्लिकेशन बंद करना चाहते हैं?",
    "youhave": "आपको",
    "newnotifications": "नई नोटिफिकेशन",
    "received": "प्राप्त हुई हैं",
    "details": "डिटेल",
    "back": "वापस जाएं",
    "gatepassmultipliermessage": "पाउच को गुणक में डालो — जैसे",
  };

  static final Map<String, String> gu = {
    "appName": "સુમુલ ગ્રાહક",
    "homeTitle": "મુખ્ય પેજ",
    "welcomeMessage": "હોમ પર આપનું સ્વાગત છે",
    "alert": "ચેતવણી",
    "error": "ભૂલ",
    "warning": "ચેતવણી",
    "success": "સફળતા",
    "required": "જરૂરી",
    "yes": "હા",
    "no": "ના",
    "ok": "બરાબર",
    "canceled": "રદ કરો",
    "save": "ઉમેરો",
    "clear": "સાફ કરો",
    "capture": "કૅપ્ચર કરો",
    "noImageCaptured": "કોઈ ફોટો કૅપ્ચર થઈ નથી",
    "settings": "સેટિંગ્સ",
    "logout": "લૉગઆઉટ",
    "submit": "સબમિટ કરો",
    "logOutText": "શું તમે ખરેખર લોગઆઉટ કરવા માંગો છો?",
    "noRecordFound": "કોઈ રેકોર્ડ મળ્યો નથી",
    "loginScreenLoginText": "લૉગિન",
    "loginScreenSignupBtnText": "સાઇનઅપ",
    "loginScreenEmailText": "ઇમેઇલ",
    "loginScreenVerifyOtpText": "ઓટિપિ ચકાસો",
    "loginScreenSendOtpBtnText": "ઓટિપિ મોકલો",
    "loginScreenResendOtpText": "ઓટિપિ ફરી મોકલો",
    "loginScreenHintMobileNumber": "મોબાઇલ નંબર",
    "loginScreenPleaseEnterUsername":
        "મહેરબાની કરીને માન્ય ગ્રાહક કોડ દાખલ કરો",
    "loginScreenEnterMobileNumber": "તમારો મોબાઇલ નંબર દાખલ કરો",
    "loginScreenSmsSentMessage": "4-અંકનો ઓટિપિ મોકલાયો છે",
    "loginScreenValidOtp": "મહેરબાની કરીને માન્ય ઓટિપિ દાખલ કરો",
    "loginScreenChange": "બદલો",
    "formVehicleNo": "વાહન નંબર",
    "formSearchVehicleNumber": "વાહન નંબર શોધો",
    "formSearchAgent": "ગ્રાહક શોધો",
    "formDate": "તારીખ",
    "formInText": "અંદર",
    "formOut": "બહાર",
    "formInDate": "અંદર ની તારીખ",
    "formOutDate": "બહાર ની તારીખ",
    "formContractor": "ઠેકેદાર",
    "formMobileNo": "મોબાઇલ નંબર",
    "formTotalTime": "કુલ સમય",
    "currentStatus": "હાલની સ્થિતિ",
    "formEmpNo": "ગ્રાહક નંબર",
    "formEmpName": "ગ્રાહકનું નામ",
    "formName": "નામ",
    "yourAgent": "તમારું ગ્રાહક",
    "categoryChooseCategory": "કેટેગરી પસંદ કરો",
    "category": "કેટેગરી",
    "categoryDairy": "ડેરી",
    "categoryOther": "અન્ય",
    "categoryBakery": "બેકરી",
    "categoryMilk": "દૂધ",
    "categorypProduct": "ઉત્પાદન",
    "apptitle1": "સુરત-તાપી ડી. કો-ઓપ. મિલ્ક પ્રોડ્યુસર યુનિયન લિ.",
    "apptitle2": "સુમુલ ડેરી, સુરત - 395 008",
    "placeOrder": "ઓર્ડર કરો",
    "dashboardBalance": "બેલેન્સ",
    "dashboardTime": "સમય",
    "total": "કુલ",
    "report": "રિપોર્ટ્સ",
    "information": "માહિતી",
    "menuHeaderOrderManagement": "ઓર્ડર મેનેજમેન્ટ",
    "menuHeaderOrderHistory": "છેલ્લો ઓર્ડર",
    "menuHeaderCashManagement": "કેશ મેનેજમેન્ટ",
    "menuHeaderReports": "રિપોર્ટ્સ",
    "menuplaceOrder": "ઓર્ડર કરો",
    "menucopyOrder": "કોપી ઓર્ડર",
    "menudailySlip": "ડેઇલી સ્લીપ",
    "menuchangepassword": "પાસવર્ડ બદલો",
    "menuchangepasswordoldpassword": "જૂનો પાસવર્ડ",
    "menuchangepasswordnewpassword": "નવો પાસવર્ડ",
    "menuchangepasswordnewcnfpassword": "પાસવર્ડની પુષ્ટિ કરો",
    "menuchangepasswordcreatenew": "નવો પાસવર્ડ બનાવો",
    "menuaboutus": "અમારા વિશે",
    "menunewsalert": "ન્યુઝ એન્ડ એલર્ટ",
    "menupricelist": "ભાવ પત્રક",
    "menuyearlystatement": "વાર્ષિક માસિક પત્રક",
    "menudatewisebalance": "તારીખ વાઈઝ બેલેન્સ",
    "menuviewgatepassorder": "ગેટપાસ ઓર્ડર જુઓ",
    "menuviewpreviousorder": "છેલ્લો ઓર્ડર જુઓ",
    "menuviewpreviousextraorder": "છેલ્લો અધિકના ઓર્ડર જુઓ",
    "menugatepassorder": "ગેટપાસ ઓર્ડર",
    "menubakeryorder": "બેકરી - ઓર્ડર (બેકરી વાહન)",
    "menuextraorder": "અધિક ઓર્ડર",
    "menucashentry": "કેશ એન્ટ્રી",
    "menuviewcashentry": "કેશ એન્ટ્રી જુઓ",
    "menuconfirmorder": "કનફર્મ ઓર્ડર",
    "menulogoutfromalldevice": "બધા ડિવાઈસમાંથી લૉગઆઉટ કરો",
    "menubacktocategory": "મુખ્ય કેટેગરી",
    "menuledger": "લેજર",
    "menucd": "ક્રે. ડેબ.",
    "menucrate": "ક્રેટ",
    "ordertime": "ઓર્ડર સમય",
    "allordertime": "બધા ઓર્ડર સમય",
    "hasended": "સમાપ્ત થઈ ગયા છે",
    "ordertimenotice": "ઓર્ડર સમય સૂચના",
    "orderAmount": "ઓર્ડર કિંમત",
    "changeDate": "તારીખ બદલો",
    "menucratebalance": "ક્રેટ બેલેન્સ",
    "pouch": "પાઉચ",
    "crates": "ક્રેટ્સ",
    "pending": "બાકી",
    "completed": "પૂર્ણ",
    "orderNo": "ઓર્ડર નંબર",
    "edit": "સુધારો",
    "qty": "ક્વોન્ટિટી",
    "currency": "ચલણ",
    "perDayLimit": "દરરોજની મર્યાદા 20000 છે",
    "cancel": "રદ કરેલું",
    "slipNo": "સ્લિપ નં",
    "denomination": "મુલ્ય",
    "nos": "સંખ્યા",
    "amount": "કિંમત",
    "openingBalance": "ડિપોઝિટ ઓપનિંગ બેલેન્સ",
    "netClosingBalance": "નેટ ક્લોઝિંગ બેલેન્સ",
    "closingLessDeposit": "ક્લોઝિંગ (લેસ ડિપોઝિટ)",
    "times": "ટાઈમ્સ",
    "routes": "રૂટ્સ",
    "dateWiseBalanceSummary": "તારીખવાર બેલેન્સ",
    "despatch": "ડિસ્પેચ",
    "deposit": "ડિપોઝિટ",
    "financialYear": "નાણાકીય વર્ષ",
    "selectMonth": "મહિનો પસંદ કરો",
    "optional": "વૈકલ્પિક",
    "month": "મહિનો",
    "download": "ડાઉનલોડ",
    "viewStatement": "સ્ટેટમેન્ટ જુઓ",
    "exitAppTitle": "એપ બંધ કરો",
    "exitAppMessage": "શું તમે ખરેખર એપ બંધ કરવા માંગો છો?",
    "youhave": "તમને",
    "newnotifications": "નવી નોટિફિકેશન",
    "received": "મળી છે",
    "details": "વિગતો",
    "back": "પાછા જાવ",
    "gatepassmultipliermessage": "પાઉચ ગુણાંકમાં નાખો — જેમ કે",
  };
}
